name:                web-scraper
version:             0.1.0.0
github:              "hbsock/web-scraper"
license:             BSD3
author:              "Hanbin Sock"
maintainer:          "hbsock@gmail.com"
copyright:           "2019 Hanbin Sock"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/hbsock/web-scraper#readme>

dependencies:
- base >= 4.7 && < 5
- http-conduit
- bytestring
- tagsoup
- text
- random
- directory
- filepath
- network-uri

library:
  source-dirs: src

executables:
  web-scraper-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - web-scraper

tests:
  web-scraper-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - web-scraper
